### PR TITLE
adding numpy adapters

### PR DESCRIPTION
**Pull request by iftahnaf**
Hi,

When trying to write ros2 bag with custom messages to Postgres, I get the following error:

`psycopg2.ProgrammingError: can't adapt type 'numpy.uint32'`

I fixed it with the [`register_adapter`](https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.register_adapter) function.

### CODE REVIEW

**Comment by suurjaak** [comment]
What is the definition of the custom message type you were attempting to write?

**Comment by iftahnaf** [comment]
It's a package with about 20 custom messages (generated from Simulink buses), most of them nested.

for example:
```
float64[3] x_i
float64[3] v_i
float64[3] x_lla
bool is_sun_eclipse
float64[3] sun_dir_b
float64[3] sun_vec_lclf
simulink_msgs/DynGravityType gravity
simulink_msgs/DynKeplerType kepler
simulink_msgs/DynStrOcclusiOnType str1_occlusion
simulink_msgs/DynStrOcclusiOnType str2_occlusion
```

**Comment by suurjaak** [comment]
I'm just curious as to where did numpy come into play. Because as far as I know, numpy is not a requirement in ROS2. 

Can you give a definition of the simplest message type that fails to write? I'd like to reproduce this problem in my own setup.

**Comment by iftahnaf** [comment]
Sorry for the late reply.

It doesn't point to a specific message, the error is popping at the end of the upload:

```
Wrote 170,769 messages in 17 topics to Postgres database postgresql://iftach@localhost/iftach.
Traceback (most recent call last):
  File "/workspaces/iftach/install/grepros/bin/grepros", line 33, in <module>
    sys.exit(load_entry_point('grepros==0.6.0', 'console_scripts', 'grepros')())
  File "/workspaces/iftach/install/grepros/lib/python3.10/site-packages/grepros/main.py", line 540, in run
    searcher.search(source, sink)
  File "/workspaces/iftach/install/grepros/lib/python3.10/site-packages/grepros/search.py", line 108, in search
    source.close(), sink.close()
  File "/workspaces/iftach/install/grepros/lib/python3.10/site-packages/grepros/outputs.py", line 560, in close
    sink.close()
  File "/workspaces/iftach/install/grepros/lib/python3.10/site-packages/grepros/plugins/auto/dbbase.py", line 130, in close
    self._executemany(sql, self._sql_queue.pop(sql))
  File "/workspaces/iftach/install/grepros/lib/python3.10/site-packages/grepros/plugins/auto/postgres.py", line 140, in _executemany
    psycopg2.extras.execute_batch(self._cursor, sql, argses)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/extras.py", line 1215, in execute_batch
    sqls = [cur.mogrify(sql, args) for args in page]
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/extras.py", line 1215, in <listcomp>
    sqls = [cur.mogrify(sql, args) for args in page]
psycopg2.ProgrammingError: can't adapt type 'numpy.float32'
```

**Comment by suurjaak** [comment]
Can you maybe share the generated simulink message package? 

If some message packages produce numpy types, it is not enough to just hack in the adapters for Postgres output, I need to introduce a more general compatibility layer.

**Comment by iftahnaf** [comment]
I'll try to generate some simple package, but none of the messages contains numpy types, only `float`, `int`, `uint`, and `bool`.

**Comment by suurjaak** [comment]
Seeing the actual Python code can be helpful still. 

However, maybe this is caused by something in your environment? Are the message packages perhaps using `rosidl_python`? It appears to provide some acceleration by using numpy types in ROS.

**Comment by iftahnaf** [comment]
The messages are in a dedicated package built with `ament_cmake` and use `rosidl_default_generators`.

There is another C++ package that uses those custom messages in the nodes. There is no direct link to any Python package.

**Comment by suurjaak** [comment]
Well there must be Python code for those packages as well, otherwise grepros would not be able to deserialize them.

You can see where the Python code is if you open a Python console, import the message package, and print `that_message_package.__file__`.

**Comment by suurjaak** [comment]
@iftahnaf  Hello?

**Comment by suurjaak** [comment]
In any case, what should work better than this patch, is replacing the following three lines from https://github.com/suurjaak/grepros/blob/master/src/grepros/ros2.py#L649-L651:

```python
    if isinstance(v, (bytes, array.array)) \
    or "numpy.ndarray" == "%s.%s" % (v.__class__.__module__, v.__class__.__name__):
        v = list(v)
```

with these:

```python
    if isinstance(v, (bytes, array.array)): v = list(v)
    elif numpy and isinstance(v, (numpy.generic, numpy.ndarray)): v = v.tolist()
```

and adding a robust import to the file header:

```python
try: import numpy
except Exception: numpy = None
```


Can you confirm?

**Comment by iftahnaf** [comment]
Sorry for the late reply, I'm away from PC (or civilization) until next week.
I'll update you asap.
Thanks again.

**Comment by suurjaak** [comment]
@iftahnaf Back to civilization?

**Comment by suurjaak** [comment]
@iftahnaf I have released grepros v1.0.0, which includes the fix for numpy types. Can you verify it works now?

Closing this pull request. Thank you.

**Pull request closed without merging**
